pipeline {
  agent any
  tools {nodejs "Node"}
  stages {
    stage('Build') {
      steps {
        git branch: 'main', url: 'https://github.com/RachanaMeda/Movie-App.git'
        sh 'npm install'
      }
    }
}
}
